[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf

monitor_speed = 115200
upload_speed = 921600

; Flash 16MB + PSRAM 8MB (N16R8)
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi

; Tham chiếu sdkconfig defaults
board_build.esp-idf.sdkconfig_defaults = sdkconfig.defaults

; ⚠️ ĐÃ XÓA -D CONFIG_FREERTOS_UNICORE (gây lỗi AMP trên ESP32-S3)
build_flags = 
    -D BOARD_HAS_PSRAM

monitor_filters = esp32_exception_decoder, colorize
