; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
; === Fix cứng port của Node A ===
upload_port = COM3
monitor_port = COM3

monitor_speed = 115200
monitor_filters = 
    esp32_exception_decoder
    time

upload_speed = 921600

lib_deps = 
    sandeepmistry/LoRa@^0.8.0
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    majicdesigns/MD_Parola
    majicdesigns/MD_MAX72XX    
    
build_flags = 
    -DCORE_DEBUG_LEVEL=3