[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

; === Fix cứng port của Node A ===
upload_port = COM11
monitor_port = COM11


; ✅ QUAN TRỌNG: khai báo đúng memory type cho N16R8 (OPI PSRAM)
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi

; Flash size 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

lib_deps = 
    sandeepmistry/LoRa@^0.8.0
    adafruit/Adafruit NeoPixel
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    marcoschwartz/LiquidCrystal_I2C
build_flags =
    -DBOARD_HAS_PSRAM
    ; -DARDUINO_USB_MODE=1
    ; -DARDUINO_USB_CDC_ON_BOOT=1