[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; ===== THƯ VIỆN =====
lib_deps =
    t-vk/ESP32 BLE Mouse@^0.3.1
    rfetick/MPU6050_light

; ===== CẤU HÌNH UPLOAD =====
monitor_speed = 115200
upload_speed = 921600

; ===== TÙY CHỌN BLUETOOTH =====
build_flags =
    -D CONFIG_BT_ENABLED=1
    -D CONFIG_BLUEDROID_ENABLED=1
