[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; ===== PORT =====
upload_port = COM11
monitor_port = COM11

; ===== SPEED =====
upload_speed = 460800
monitor_speed = 115200

; ===== USB CDC (QUAN TRỌNG NHẤT) =====
board_build.cdc_on_boot = 1
board_build.usb_mode = 1   ; 👈 BẮT BUỘC (đổi từ 0 -> 1)

; ===== CPU / FLASH =====
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_size = 16MB
board_upload.flash_size = 16MB

; ===== PSRAM =====
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
build_flags = 
    -D BOARD_HAS_PSRAM=1
    -D USE_NIMBLE          ; ← dòng này bật NimBLE
; ===== FIX SERIAL RESET =====
monitor_rts = 0
monitor_dtr = 0

; ===== LIB =====
lib_deps = 
    bodmer/TFT_eSPI@^2.5.43
    t-vk/ESP32 BLE Keyboard@^0.3.2
    h2zero/NimBLE-Arduino@^1.4.0   ; ← thêm thư viện này
    bblanchon/ArduinoJson@^7.1.0
