[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    majicDesigns/MD_Parola @ ^3.7.3
    majicDesigns/MD_MAX72XX @ ^3.5.0
    electroniccats/MPU6050 @ ^1.4.0